// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyFrCnsuAlnqjfcMQ4h1keQ8ooICX7g8',
    appId: '1:1035093977226:web:0b6c3ddce2493c81372573',
    messagingSenderId: '1035093977226',
    projectId: 'abc-interview',
    authDomain: 'abc-interview.firebaseapp.com',
    storageBucket: 'abc-interview.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vUN7fk10MsM-RAEl7bysF0gjqzFS00E',
    appId: '1:1035093977226:android:ea49d70cf62f5a40372573',
    messagingSenderId: '1035093977226',
    projectId: 'abc-interview',
    storageBucket: 'abc-interview.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCY5bvcsmxunQW1xJ7mGD3Mv2yUhKcbQI',
    appId: '1:1035093977226:ios:c94161a21dc3d4ce372573',
    messagingSenderId: '1035093977226',
    projectId: 'abc-interview',
    storageBucket: 'abc-interview.firebasestorage.app',
    iosBundleId: 'com.example.coderebased',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCY5bvcsmxunQW1xJ7mGD3Mv2yUhKcbQI',
    appId: '1:1035093977226:ios:c94161a21dc3d4ce372573',
    messagingSenderId: '1035093977226',
    projectId: 'abc-interview',
    storageBucket: 'abc-interview.firebasestorage.app',
    iosBundleId: 'com.example.coderebased',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHyFrCnsuAlnqjfcMQ4h1keQ8ooICX7g8',
    appId: '1:1035093977226:web:be235f59b88f1b9d372573',
    messagingSenderId: '1035093977226',
    projectId: 'abc-interview',
    authDomain: 'abc-interview.firebaseapp.com',
    storageBucket: 'abc-interview.firebasestorage.app',
  );
}
